---
- name: install nginx
  yum: name=nginx state=present

- name: copy nginx configuration
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
   - { src: "default.conf", dest: "/etc/nginx/conf.d/default.conf" }
   - { src: "nginx.conf", dest: "/etc/nginx/nginx.conf" }

- name: start nginx
  sudo: yes
  command: service nginx restart
