---
- name: install nginx
  yum: name=nginx state=present

- name: copy nginx configuration
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
   - { src: "default.conf", dest: "/etc/nginx/conf.d/default.conf" }
   - { src: "nginx.conf", dest: "/etc/nginx/nginx.conf" }

- name: generate SSL configuration
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=orange-secure.amida-demo.com" -days 3650 -keyout /etc/nginx/ssl.key -out /etc/nginx/ssl.crt -extensions v3_ca creates=/etc/nginx/ssl.crt

- name: start nginx
  sudo: yes
  command: service nginx restart
