language: node_js
node_js:
    - "0.10"
services:
    - mongodb
install:
  - sudo apt-get update
  - sudo apt-get install libzmq3-dev
  - sudo pip install -r lib/matching/requirements.txt
  - npm install -g grunt-cli
  - npm install
  - echo "0123456789abcdef" > .secret
script: grunt test
after_success: grunt coverage:push
