language: node_js
node_js:
    - "0.10"
sudo: false # use container-based infrastructure
services:
    - mongodb
addons:
    apt:
        packages:
         - libzmq3-dev
         - python-virtualenv

# cache node and python installs
cache:
    directories:
        - $HOME/.cache/pip
        - venv/.cache/pip
        - $HOME/.pip-cache/
        - /home/travis/virtualenv/python2.7
        - node_modules

# setup python virtualenv so we can pip install packages without
# sudo
before_install:
  - virtualenv venv
  - source venv/bin/activate

# install python and node prereqs
install:
  - source venv/bin/activate
  - pip install -r lib/matching/requirements.txt --download-cache $HOME/.pip-cache
  - npm install -g grunt-cli
  - npm install

# setup config to test with
before_script:
  - cp config.js.example config.js

# run e2e & unit tests
script:
  - grunt test

# instrument code and run tests against instrumented code, then
# push to coveralls.io
after_success:
  - grunt coverage:push
