language: node_js
node_js:
    - "0.10"
services:
    - mongodb
install:
  - sudo apt-get update
  - sudo apt-get install libzmq3-dev
  - sudo pip install zerorpc python-dateutil pytz termcolor
  - npm install -g grunt-cli
  - npm install
script: grunt test
after_success: grunt coverage:push
