---
#file: roles/orange/tasks/deploy.yml
- name: Remove old source and current folder
  command: rm -rf "/var/www/oramge/source" "/var/www/orange/current"

- name: Make new source and current folder
  command: mkdir -p "/var/www/orange/source" "/var/wwww/orange/current"

- name: Clone Orange repository
  git: repo="https://github.com/amida-tech/orange-api.git" dest="/var/www/orange/source"

- name: Copy Orange source to current
  command: cp -r /var/www/orange/source/. /var/www/orange/current

- name: Create secret
  sudo: yes
  command: su -c "echo \"{{ secret }}\" > /var/www/orange/shared/.secret"

- name: Link secret from shared to current
  command: ln -sf /var/www/orange/shared/.secret /var/www/orange/current/.secret

- name: Install python dependencies
  sudo: yes
  command: pip install -r /var/www/orange/current/lib/matching/requirements.txt

- name:  Install orange dependencies
  command: npm install --production chdir=/var/www/orange/current 

- name: Copy matcher init.d script
  template: src="matcher.init.d" dest="/etc/init.d/orange-matcher"

- name: Install matcher init.d script
  sudo: yes
  command: "{{ item }}"
  with_items:
   - chmod +x /etc/init.d/orange-matcher
   - chkconfig orange-matcher on
