---
#file: roles/common/orange/main.yml

- name: download docker compose
  shell: curl -L https://github.com/docker/compose/releases/download/1.3.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

- name: make docker compose executable
  shell: chmod +x /usr/local/bin/docker-compose

- name: create build directory
  file: >
    dest="/src/"
    state=directory

- name: clone orange repo
  git: >
    repo="https://github.com/amida-tech/orange-api.git"
    dest="/src/orange"

- name: copy docs over from gh-pages branch
  shell: chdir=/src/orange git fetch origin gh-pages:gh-pages && git checkout gh-pages -- index.html && mkdir -p docs/output && mv index.html docs/output/

- name: copy config file
  shell: chdir=/src/orange cp config.js.example config.js

- name: build image (first run may be slow whilst building without a cache)
  shell: chdir=/src/orange/deploy /usr/local/bin/docker-compose build

- name: start image (first run may be slow whilst downloading images)
  shell: chdir=/src/orange/deploy /usr/local/bin/docker-compose up -d
